- src/Codeception/Module/Symfony.php
I also have this issue @Naktibalda 
Credits to @burned42 and his comment here https://github.com/Codeception/module-symfony/issues/1#issuecomment-553408894
> refactor: runSymfonyConsoleCommand

- .github/workflows/main.yml
- composer.json
See https://github.com/Codeception/Codeception/issues/5890
> Replace Travis by Github Actions

- src/Codeception/Lib/Connector/Symfony.php
> Fix connector code style

- documentation.md
- src/Codeception/Module/Symfony.php
[Also present](https://github.com/Codeception/module-laravel5/blob/bd2c604e8aa02d2b24737de01c6716473e8db96c/src/Codeception/Module/Laravel5.php#L992) in the Laravel Module.
To do: if this is merged I'll make sure it works with both entities and tables, for the moment this is the MVP.
> Added seeNumRecords function

- documentation.md
- src/Codeception/Module/Symfony.php
Replaces #12, #13, #14, #15, #16, #17 and #18
cc: @TavoNiievez
> TavoNiievez features

- src/Codeception/Module/Symfony.php
Adding an even more descriptive comment - follow-up of https://github.com/Codeception/module-symfony/pull/9/commits/2f8467151b5228335cc167263a98b5e6386573b3
The indentation of the code is preserved in the displayed message, so it looked like this:
```
Fail  Emails can't be tested without SwiftMailer connector.
If you are using Symfony Mailer define mailer: "symfony_mailer" in Symfony module config.
```
I hope the `\n` works better :-)
> Improved seeEmailIsSent error message

- src/Codeception/Module/Symfony.php
Explaining test.service_container
> Improved description of grabService

- src/Codeception/Module/Symfony.php
Added info about Console, see https://github.com/Codeception/Codeception/issues/4698
> Docs: improved seeEmailIsSent description

- .gitattributes
- .github/workflows/main.yml
- .travis.yml
- composer.json
- readme.md
- src/Codeception/Module/Symfony.php
These versions have not been supported for a long time, it does not make sense to run tests on them in this module, or limit development for compatibility with these versions without security support.
So... with this PR:
> Remove php 5.6 and Symfony 2.8 support

- src/Codeception/Module/Symfony.php
$this->fail() stops the execution of the test, so these lines are unnecessary.
> Removed extra return statements

- src/Codeception/Module/Symfony.php
Calling:
```php
$this->client->getResponse();
```
results in:
```
[BadMethodCallException] The "request()" method must be called before "AbstractBrowser::getRe
sponse()".
```
so this is never reached:
```php
if (null === $response) {
$this->fail("You must perform a request before using this method.");
}
return $profiler->loadProfileFromResponse($response);
```
> fix getProfile logic

- composer.json
Codeception [now supports](https://github.com/Codeception/Codeception/pull/6015) `vlucas/phpdotenv` v5, so now it can be allowed here too.
> Allow vlucas/phpdotenv v5

- src/Codeception/Module/Symfony.php
`$I->grabRepository` significantly improves the readability of the tests that communicate with the database :)
as mentioned in the docblock, it works with:
```php
$userRepository = $I->grabRepository($user);
```
```php
$userRepository = $I->grabRepository(User::class);
```
```php
$userRepository = $I->grabRepository(UserRepository::class);
```
```php
$userRepository = $I->grabRepository(UserRepositoryInterface::class);
```
It also includes validations in case of incorrect data and fails the test showing a corresponding error message.
@Naktibalda
> Added grabRepository function

- src/Codeception/Module/Symfony.php
`$I->seePageIsAvailable()` allows to do in a line of code what is normally done like this: [[See source](https://github.com/symfony/demo/blob/bb3b1834079e1af8a65786b48415c8147fc7ee10/tests/Controller/DefaultControllerTest.php#L52)]
```php
public function testPublicBlogPost(): void
{
$client = static::createClient();
$blogPost = $client->getContainer()->get('doctrine')->getRepository(Post::class)->find(1);
$client->request('GET', sprintf('/en/blog/posts/%s', $blogPost->getSlug()));
$this->assertResponseIsSuccessful();
}
```
while `$I->seePageRedirectsTo()` allows to do in a line of code what is normally done in this way: [[See source](https://github.com/symfony/demo/blob/bb3b1834079e1af8a65786b48415c8147fc7ee10/tests/Controller/DefaultControllerTest.php#L69)]
```php
public function …
```
> Added availability check functions

- src/Codeception/Module/Symfony.php
While testing forms in Symfony it is very common to have to repeat the form name in different places in the method to comply with **the Symfony naming format**:
```php
$I->submitForm('form[name={form_name}]', [
'{form_name}[{field_key}]' => '{field_value}',
'{form_name}[{field_key}]' => '{field_value}'
], '{form_name}_submit');
```
However this **ruins the readability of the test** and makes the code much more verbose:
```php
$I->submitForm('form[name=user_update_password_form]', [
'user_update_password_form[oldPassword]'      => '123456',
'user_update_password_form[password][first]'  => '654321',
'user_update_password_form[password][second]' => '654321'
], 'user_update_password_form_submit');
```
That is why i write this function that allows you to take advantage of the fact that the …
> Added submitSymfonyForm function

- src/Codeception/Module/Symfony.php
Method to verify that the user's password would not benefit from rehashing.
```php
$I->seeUserPasswordDoesNotNeedRehash();
$I->seeUserPasswordDoesNotNeedRehash($user);
```
If the user is not specified it is taken from the session.
> Added seeUserPasswordDoesNotNeedRehash function

- composer.json
- src/Codeception/Lib/Connector/Symfony.php
- src/Codeception/Module/Symfony.php
**composer.json**
* Added `"ext-json": "*"` because `json_encode` is used in `seeNumRecords`.
**src/Codeception/Lib/Connector/Symfony.php**
* Added strict types:  `declare(strict_types=1);`
* `array_keys` was used in `rebootKernel`'s foreach because it was only necessary to know the keys in that loop.
**src/Codeception/Module/Symfony.php**
* Added strict types:  `declare(strict_types=1);`
* `array_keys` was used in `_after`'s foreach because it was only necessary to know the keys in that loop.
* Imported classes with the `use` statement whenever possible
* `self::class` instead of `__CLASS__`.
* Added types to the arguments whenever possible, and explicit type cast when it was necessary.
* Used PHP if/else shorthand in `seeAuthentication` and `dontSeeAuthentication`.
> Update code standards to PHP 7.0+

- src/Codeception/Module/Symfony.php
<b>TL;DR:</b> The validation that the service exists was already done when obtaining the service. The code that is removed in this PR was not necessary.
<details>
<summary>Click to see full description.</summary>
<br/>
$this->grabService() validates that the service exists and otherwise fails the test showing a very descriptive message.
https://github.com/Codeception/module-symfony/blob/b65b2c709c8d3474e5f820909d7d7679e147de7a/src/Codeception/Module/Symfony.php#L597-L606
I had ignored that this implicit validation already existed when writing the functions that i edit in this PR: <br/>
logout, seeInSession, amOnAction, seeAuthentication, seeUserHasRole, dontSeeAuthentication, grabParameter, seeCurrentActionIs, seeUserPasswordDoesNotNeedRehash, amLoggedInAs.
</details>
> Removed superfluous service validation logic

- src/Codeception/Module/Symfony.php
**TL:DR**: I have ready PRs that will make use of this function. It is for internal use only. Some functions are present in the Laravel module and need symfony collectors. This will avoid repeating validation code like in #44.
<details>
<summary>Clic to see full description</summary>
<br/>
I'm writing at least 4 functions related to form errors that are already available in the Laravel module:
- seeFormHasErrors()
- dontSeeFormErrors()
- seeFormErrorMessages()
- seeFormErrorMessage()
And others totally new functions like:
- dontSeeMissingTranslations();
- seeEventWasTriggered();
- dontSeeDeprecations();
Since all these functions will need their respective collectors of the Symfony Profiler, it is necessary to have a function that validates that it exists and fails the test otherwise,
With …
> Added grabCollector function

- src/Codeception/Module/Symfony.php
Now that the minimum version of php for this module is php 7.0.8 this conditional is never used
> Remove outdated php5 logic

- src/Codeception/Module/Symfony.php
It is [also present](https://github.com/Codeception/module-laravel5/blob/1d8a82f78a6e8c26f49af65d9001fa311785d54b/src/Codeception/Module/Laravel5.php#L661) in the Laravel Module,
Check for errors after submitting a form.
> Added seeFormHasErrors function

- src/Codeception/Module/Symfony.php
> Fix seeEmailIsSent 

- src/Codeception/Module/Symfony.php
```php
$I->seeFormErrorMessage('username');
$I->seeFormErrorMessage('username', 'Username is empty');
```
[Also present](https://github.com/Codeception/module-laravel5/blob/1d8a82f78a6e8c26f49af65d9001fa311785d54b/src/Codeception/Module/Laravel5.php#L726) in the Laravel module... But a bit more complex 😃.
- Fails if there are no forms when asserting.
- Fails if an invalid field is passed as an argument.
- It performs its function by verifying that the field is valid and has errors.
- If the expected error message is specified it verifies that it matches the current one. (technically with: `->assertStringContainsString()`).
> Added seeFormErrorMessage function

- src/Codeception/Module/Symfony.php
Object validation must be done before interface validation.
This is because `interface_exists` expects a string as a parameter.
> fix grabRepository logic

- src/Codeception/Module/Symfony.php
In Linux, the `basename` function may have a different behavior from windows and other systems.
The conditional now verifies that the `$controller` string ends in the expected `$action` string, which has the same effect.
test-based fix.
> Fix strategy to match actions

- .github/workflows/main.yml
- composer.json
All dependencies actually work on PHP8, some of them just haven't updated version requirement in their composer.json
> Support PHP 8

- .github/workflows/main.yml
> Updated Test Project

- composer.json
In accordance with what is mentioned in (#39) this module proceeds to progressively remove support for obsolete versions of PHP.
This time 7.0, which has not had any kind of support for 2 years.
> Remove PHP 7.0 support

- src/Codeception/Module/Symfony.php
`seeInSession()` was already there, but the opposite was missing.
I omitted the `$value` parameter for this reason: If `$attribute` is *not* in the session, it doesn't make much sense to do an additional check about its (inexistent) value. Or does it?
Tests are missing, but I don't know how to do that :-(
> Adding `dontSeeInSession()`

- src/Codeception/Module/Symfony.php
This logic is not necessary since this module no longer supports Symfony versions lower than 3.4
The `->getValue()` method always exists and therefore it is safe to remove these internal functions.
> Remove outdated Symfony 3 logic

- src/Codeception/Module/Symfony.php
With this PR the parameter flags of the authentication methods are removed (`$remembered` in this case), in addition, the following functions are added:
```php
public function seeRememberedAuthentication()
public function dontSeeRememberedAuthentication()
```
In order to supplement the previous functionality.
It's only a **BC** if you used `seeAuthentication` or `dontSeeAuthentication` with `true` as an argument.
> Remove param flags from authentication methods

- src/Codeception/Module/Symfony.php
With this PR the parameter flag `$isPermanent` is removed from the `persistService()`
And a separate function is added to replace its functionality:
```php
public function persistPermanentService(string $serviceName)
```
> Remove param flag from persistService function

- src/Codeception/Module/Symfony.php
It [is also present](https://github.com/Codeception/module-laravel5/blob/1d8a82f78a6e8c26f49af65d9001fa311785d54b/src/Codeception/Module/Laravel5.php#L1027) in the Laravel module.
Once it was added, it was possible to use it in `seeNumRecords`.
> Added grabNumRecords function

- src/Codeception/Module/Symfony.php
It [is also present](https://github.com/Codeception/module-laravel5/blob/1d8a82f78a6e8c26f49af65d9001fa311785d54b/src/Codeception/Module/Laravel5.php#L374) in the Laravel module.
The symfony translation was a bit more complex, since there is no method to directly ask if an event was fired.
In any case, i was able to get the same behavior.
> Added seeEventTriggered function

- src/Codeception/Module/Symfony.php
Exactly the same method that [is already present](https://github.com/Codeception/module-laravel5/blob/1d8a82f78a6e8c26f49af65d9001fa311785d54b/src/Codeception/Module/Laravel5.php#L639) in the Laravel module.
> Added seeSessionHasValues function

- src/Codeception/Module/Symfony.php
I looked in the [history of the TimeDataCollector](https://github.com/symfony/http-kernel/blob/5.x/DataCollector/TimeDataCollector.php) and it never got called `'timer'` as well as it never had a method called `->getTime()` so i guess this never worked before.
I also added the missing docblock.
> Fix time collector logic when debugging

- .github/workflows/main.yml
- composer.json
- readme.md
- src/Codeception/Module/Symfony.php
This is the last PR that aims to put the supported PHP versions in sync with the versions required by this module.
[Rector](https://github.com/rectorphp/rector), [Psalm](https://github.com/vimeo/psalm), [Phpmd](https://github.com/phpmd/phpmd), [PHP Code Sniffer](https://github.com/squizlabs/PHP_CodeSniffer) and [PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) were executed to guarantee a consistent code.
> Remove support for PHP 7.1 and PHP 7.2

- src/Codeception/Module/Symfony.php
For remembered authentication methods `seeRememberedAuthentication` and `dontSeeRememberedAuthentication`, there are some cases in which it is necessary to verify not only the role but also the generated Cookie, that is why this logic is added to these methods.
Also, to add more clarity about the internals of these methods, the class constants of the Symfony Security component are used to make these assertions.
> Add cookie validation to auth methods

- src/Codeception/Module/Symfony.php
It is [also present](https://github.com/Codeception/module-laravel5/blob/1d8a82f78a6e8c26f49af65d9001fa311785d54b/src/Codeception/Module/Laravel5.php#L701) in the Laravel module.
A validation was added to allow omitting `=> null` in the array if you don't want to specify the error message.
> Added seeFormErrorMessages function

- src/Codeception/Module/Symfony.php
- src/Codeception/Module/Symfony/MailerAssertionsTrait.php
- src/Codeception/Module/Symfony/ServicesAssertionsTrait.php
Just to be consistent, the `services` part is updated, which is the only one documented (and useful?).
The `email` part was never documented (or used?), so that excess annotation is removed as well.
> Update the `services` Part

- src/Codeception/Module/Symfony.php
- src/Codeception/Module/Symfony/MailerAssertionsTrait.php
In this PR:
- Support for Swift Mailer is removed.
- The `mailer:` config parameter is removed since it is no longer needed.
- Now it is possible to assert emails sent from Symfony commands.
- The **Profiler** is replaced by Mail Logger to do the email assertions since the profiler requires 'requests' to be made and that is not always a requirement to send emails in Symfony.
The fewest possible changes were made to the API to make it easier for users to upgrade to version 2.
The most significant change, however, is that `seeEmailIsSent` now defaults to `1` instead of `null`. This change is made because previously an assert of type `assertGreatherThan` was made, whereas now, the `EmailCount Constraint` requires that the expected number of emails be specified.
Checking the exact amount of …
> Refactor email assertions

- src/Codeception/Module/Symfony.php
- src/Codeception/Module/Symfony/ConsoleAssertionsTrait.php
- src/Codeception/Module/Symfony/EventsAssertionsTrait.php
- src/Codeception/Module/Symfony/FormAssertionsTrait.php
- src/Codeception/Module/Symfony/MailerAssertionsTrait.php
- src/Codeception/Module/Symfony/ParameterAssertionsTrait.php
- src/Codeception/Module/Symfony/RouterAssertionsTrait.php
- src/Codeception/Module/Symfony/SecurityAssertionsTrait.php
- src/Codeception/Module/Symfony/ServicesAssertionsTrait.php
- src/Codeception/Module/Symfony/SessionAssertionsTrait.php
Using strings like `'security.helper'` to get services (or collectors) in multiple places was a bad practice.
So in this PR, these identifiers are encapsulated in their own function cohesive to the trait to which they belong.
If one of them changes in the future, only one line of code needs to be changed.
> Encapsulate services and collectors

- .github/workflows/main.yml
- src/Codeception/Lib/Connector/Symfony.php
- src/Codeception/Module/Symfony.php
With this PR:
- The new minimum supported version is Symfony 4.4.
- All logic and docs that reference Symfony 3.4 are removed.
- Now `_getContainer` returns the test container first if it exists.
- `getPossibleKernelClasses` and `initializeSymfonyCache` methods removed.
- Removed the `var_path` config parameter.
> Remove Symfony 3.4 Support

- src/Codeception/Module/Symfony/MailerAssertionsTrait.php
- Added `grabSentEmails` function.
- Added `grabLastSentEmail` function.
Both are available in the Yii2 module: [here](https://github.com/Codeception/module-yii2/blob/77ef7516cf13c3813d7bdb63a406820b138e74ae/src/Codeception/Module/Yii2.php#L774) and [here](https://github.com/Codeception/module-yii2/blob/77ef7516cf13c3813d7bdb63a406820b138e74ae/src/Codeception/Module/Yii2.php#L794).
> Added grabEmail* functions

- src/Codeception/Module/Symfony/EventsAssertionsTrait.php
Methods for asserting on orphan events are added and documented.
> Added orphan events assertions

- src/Codeception/Module/Symfony/ConsoleAssertionsTrait.php
- src/Codeception/Module/Symfony/DoctrineAssertionsTrait.php
- src/Codeception/Module/Symfony/FormAssertionsTrait.php
- src/Codeception/Module/Symfony/RouterAssertionsTrait.php
- src/Codeception/Module/Symfony/SessionAssertionsTrait.php
- src/Codeception/Module/Symfony/TwigAssertionsTrait.php
In the past, strict types were implemented, parameters were typed, and framework calls included explicit casts.
It is time to make use of this design in assertions as well.
> Use AssertSame instead of AssertEquals

- composer.json
This module needs the profiler to a large extent, and you will generally need the assertions module after using some `grab` method so both packages are added as suggested installations.
> Add suggested packages to `composer.json`

- src/Codeception/Module/Symfony/BrowserAssertionsTrait.php
I have been monitoring the use of this method in the public repositories that use this module. 
I'm glad to see that it quickly became a very popular assertion. This is mainly because it is more natural to talk about available pages than 2xx response codes.
However, I have seen that in many cases `amOnPage` is used as a previous step, perhaps because it is more natural to read them separately. To avoid redundancies, the `$url` parameter will be optional, so both ways (the current one with a parameter, and the new one, without it) will be valid no matter which one you choose to use.
> Make url parameter optional in `seePageIsAvailable`

- composer.json
- src/Codeception/Module/Symfony/MailerAssertionsTrait.php
`Codeception/lib-innerbrowser` implemented redirection methods since [version 1.4.0](https://github.com/Codeception/lib-innerbrowser/releases/tag/1.4.0), therefore, the symfony module no longer needs to use the methods of the REST module to stop redirects when asserting about emails.
> Remove REST module as dev dependency

- src/Codeception/Module/Symfony/EventsAssertionsTrait.php
With this PR I improve the documentation of the assertions for the orphan events added in #111, with this (hopefully) I simplify the explanation while using the appropriate names.
Unlike 'normal' events the assertion for orphan events does not semantically benefit from including the suffix 'Triggered', for that reason:
I rename `seeOrphanEventTriggered` to `seeOrphanEvent` and `dontSeeOrphanEventTriggered` to `dontSeeOrphanEvent`.
Since the old names were never released in a tagged version it is not considered a BC.
Finally, I find it useful that the `dontSeeOrphanEvent` assertion can be called without any argument, therefore I make the $expected parameter optional there.
> Better explain orphan events

- src/Codeception/Module/Symfony/MailerAssertionsTrait.php
See https://github.com/Codeception/module-symfony/pull/107#issuecomment-799069222
This sentence is meant to be copied to all email-related functions:
* seeEmailIsSent
* dontSeeEmailIsSent
* grabSentEmails
* grabLastSentEmail
> Explaining the stopFollowingRedirects() restriction for email

- src/Codeception/Module/Symfony/MailerAssertionsTrait.php
Follow-up of https://github.com/Codeception/module-symfony/pull/120
> Added 'See also' in related email functions

- src/Codeception/Module/Symfony.php
- src/Codeception/Module/Symfony/BrowserAssertionsTrait.php
- src/Codeception/Module/Symfony/MailerAssertionsTrait.php
- src/Codeception/Module/Symfony/SessionAssertionsTrait.php
`example.com` is the "official" domain for such things: http://example.com/
For the removal, see https://github.com/Codeception/module-symfony/pull/120#issue-593067918
> Standardize "@example.com" as domain in documentation

- src/Codeception/Module/Symfony.php
I'd like to drop all those pages completely:
* https://codeception.com/for/symfony
* https://codeception.com/for/laravel
* etc.
I'm starting with Symfony (to show it's possible), and hopefully can motivate others to do the same for the other frameworks :-)
Reasons:
* Three pages explaining how to use Codeception with Symfony (each differently) are two too much :-) https://codeception.com/docs/modules/Symfony and https://codeception.com/for/symfony and https://codeception.com/09-04-2015/using-codeception-for-symfony-projects.html
So the module page should be the only one, and it should contain everything.
* "use cases" is a misleading title for it; in fact it's just about frameworks ;-) WordPress and Joomla are exceptions - so if it's not possible to integrate them elsewhere, they can stay …
> Added info from the 'Codeception for Symfony' page

- src/Codeception/Module/Symfony/MailerAssertionsTrait.php
Follow-up of https://github.com/Codeception/module-symfony/issues/125. My plan would be to copy this line to all email-related functions. Questions:
1. Is `^1.6` right?
2. The `mailer` configuration was never documented anywhere. But in v1.6, Swift Mailer is the default anyway, right? So this configuration is only relevant for people who still have v1.6 but use Symfony Mailer? And in this case, the better advice is to upgrade to v2, rather than configuring `mailer`?
> Mentioning Symfony Mailer requirement in v2.0.0

- src/Codeception/Module/Symfony/BrowserAssertionsTrait.php
I'm not sure about this!
But I think the submitted fieldname now is `myFormaddress`, instead of `myForm[address]` - that's what I'm trying to fix.
I didn't take a look at the tests you mentioned in https://github.com/Codeception/module-symfony/issues/54
BTW: I was first looking for this method in `FormAssertionsTrait.php`, is there a reason why you put it into `BrowserAssertionsTrait.php`?
> submitSymfonyForm(): Mentioning `name` attribute

- src/Codeception/Lib/Connector/Symfony.php
- src/Codeception/Module/Symfony.php
Fix alias name for Doctrine Connection service. Now `\Doctrine\DBAL\Connection` retreived from `_getEntityManager()->getConnection()` and `grabService(\Doctrine\DBAL\Connection)` are different which is a bug.
> Fix Doctrine Connection service alias

- src/Codeception/Module/Symfony.php
- src/Codeception/Module/Symfony/TimeAssertionsTrait.php
Code Example:
```php
$I->amOnPage('/dashboard');
$I->seeRequestTimeIsLessThan(40.5);
```
> Added seeRequestTimeIsLessThan function

- .github/workflows/main.yml
- src/Codeception/Module/Symfony/SecurityAssertionsTrait.php
- src/Codeception/Module/Symfony/SessionAssertionsTrait.php
See https://github.com/symfony/symfony/issues/39698 .
> Added Symfony 5.3 support

- src/Codeception/Module/Symfony/SessionAssertionsTrait.php
Now that a simpler interface for logging out [is being discussed in Symfony](https://github.com/symfony/symfony/issues/40663), I think it's a good time to clarify that there are two ways to log out in a functional test.
One is by going the logout path,
and the other is by invalidating the session and expiring the cookies 'manually' or _'programmatically'_.
> Added logout by path

- src/Codeception/Module/Symfony.php
- src/Codeception/Module/Symfony/MimeAssertionsTrait.php
New assertions:
- `assertEmailAddressContains`
- `assertEmailAttachmentCount`
- `assertEmailHasHeader`
- `assertEmailHeaderNotSame`
- `assertEmailHeaderSame`
- `assertEmailHtmlBodyContains`
- `assertEmailHtmlBodyNotContains`
- `assertEmailNotHasHeader`
- `assertEmailTextBodyContains`
- `assertEmailTextBodyNotContains`
All of them were already available in `symfony/framework-bundle`, however, until now it was not possible to use them with the '`$I->assert...`' syntax.
Since they are intended (but not limited) to be used in unit tests, the 'assert' prefix is ​​kept.
> Added assertions for Symfony Mime component

- .github/workflows/main.yml
- composer.json
- src/Codeception/Lib/Connector/Symfony.php
- src/Codeception/Module/Symfony.php
- src/Codeception/Module/Symfony/BrowserAssertionsTrait.php
- src/Codeception/Module/Symfony/DoctrineAssertionsTrait.php
- src/Codeception/Module/Symfony/FormAssertionsTrait.php
- src/Codeception/Module/Symfony/MailerAssertionsTrait.php
- src/Codeception/Module/Symfony/RouterAssertionsTrait.php
- src/Codeception/Module/Symfony/SecurityAssertionsTrait.php
- src/Codeception/Module/Symfony/ServicesAssertionsTrait.php
- src/Codeception/Module/Symfony/SessionAssertionsTrait.php
- Typed properties are added.
- PHP 8.1 is added to the CI.
> Update codebase to PHP 7.4

- .github/workflows/main.yml
- src/Codeception/Module/Symfony/FormAssertionsTrait.php
- src/Codeception/Module/Symfony/SessionAssertionsTrait.php
> Symfony 6 Support: Form and Session Assertions

- .github/workflows/main.yml
- composer.json
- readme.md
- src/Codeception/Module/Symfony.php
> Improved support for Codeception 5/PHP 8

- composer.json
v4 added support for PHPUnit v10 (https://github.com/Codeception/lib-innerbrowser/releases/tag/4.0.0)
> Allow installation of codeception/lib-innerbrowser v4

- src/Codeception/Module/Symfony/EventsAssertionsTrait.php
Hi! This PR is a follow-up to #168.
It includes only `seeEventTriggered`/`dontSeeEventTriggered` deprecation. And introduces new names for them: `seeEventListenerIsCalled`/`dontSeeEventListenerIsCalled`.
> Deprecate event triggered assertions

- src/Codeception/Module/Symfony/BrowserAssertionsTrait.php
- src/Codeception/Module/Symfony/ConsoleAssertionsTrait.php
- src/Codeception/Module/Symfony/DoctrineAssertionsTrait.php
- src/Codeception/Module/Symfony/EventsAssertionsTrait.php
- src/Codeception/Module/Symfony/FormAssertionsTrait.php
- src/Codeception/Module/Symfony/MailerAssertionsTrait.php
- src/Codeception/Module/Symfony/ParameterAssertionsTrait.php
- src/Codeception/Module/Symfony/RouterAssertionsTrait.php
- src/Codeception/Module/Symfony/ServicesAssertionsTrait.php
- src/Codeception/Module/Symfony/SessionAssertionsTrait.php
- src/Codeception/Module/Symfony/TimeAssertionsTrait.php
- src/Codeception/Module/Symfony/TwigAssertionsTrait.php
Small code cleanup that I considered necessary to do before evaluating the compatibility of the module with Symfony 6.3, 6.4 and 7.0
> Various improvements

- .github/workflows/main.yml
- src/Codeception/Module/Symfony/EventsAssertionsTrait.php
Hi! Currently, `seeEventTriggered` and `dontSeeEventTriggered` are actually checking if Event Listener was called. 
So I've marked these methods as deprecated and created new ones for the Listeners with more intuitive names:
* `seeEventListenerCalled`
* `dontSeeEventListenerCalled`
Additionally, I've added methods to check if Events were dispatched (named them in a way like `seeOrphanEvent`):
* `seeEvent`
* `dontSeeEvent`
[Tests](https://github.com/Codeception/symfony-module-tests/compare/main...xEdelweiss:symfony-module-tests:new_event_assertions) can be updated if you approve this PR.
> Update event assertions

- src/Codeception/Module/Symfony/EventsAssertionsTrait.php
Hi! This is a follow-up for #168. In this update, I've added the `seeEvent`/`dontSeeEvent` methods, which check if an event was dispatched without considering whether the listener processed it. 
This approach allows the assertion to cover both orphan and non-orphan events. Therefore, this should help keep tests "green" during development, especially in scenarios where listeners might be added after the event's introduction.
Additionally, this PR consolidates `assertEventTriggered` and `assertEventNotTriggered` into a single method to reduce duplication, as the method became a bit more complex.
[PR with tests.](https://github.com/Codeception/symfony-module-tests/pull/25)
> Add seeEvent/dontSeeEvent event assertions

- .github/workflows/main.yml
- LICENSE
- composer.json
- readme.md
- src/Codeception/Lib/Connector/Symfony.php
- src/Codeception/Module/Symfony.php
- src/Codeception/Module/Symfony/BrowserAssertionsTrait.php
- src/Codeception/Module/Symfony/EventsAssertionsTrait.php
- src/Codeception/Module/Symfony/FormAssertionsTrait.php
- src/Codeception/Module/Symfony/MailerAssertionsTrait.php
- src/Codeception/Module/Symfony/MimeAssertionsTrait.php
- src/Codeception/Module/Symfony/ParameterAssertionsTrait.php
- src/Codeception/Module/Symfony/RouterAssertionsTrait.php
- src/Codeception/Module/Symfony/SecurityAssertionsTrait.php
- src/Codeception/Module/Symfony/SessionAssertionsTrait.php
- src/Codeception/Module/Symfony/TimeAssertionsTrait.php
- src/Codeception/Module/Symfony/TwigAssertionsTrait.php
This PR also removes support for PHP 8.0 and unsupported versions of Symfony.
> Symfony 6.4 Support

- src/Codeception/Module/Symfony/SecurityAssertionsTrait.php
Fixes https://github.com/Codeception/module-symfony/issues/174
> Fix return type of grabSecurityService() for compatibility with symfony 7.0

- src/Codeception/Module/Symfony/RouterAssertionsTrait.php
The following test fails:
```php
$I->amOnRoute('payment_history', ['month' => '2020-07', '_fragment' => 'content']);
$I->seeCurrentRouteIs('payment_history');
```
With:
```
Step  See current route is "payment_history"
Fail  The "/payment-history/2020-07#content" url does not match with any route
```
> Ignore fragments when checking routes

- src/Codeception/Module/Symfony/ConsoleAssertionsTrait.php
> Fix: runSymfonyConsoleCommand ignores specific options

- composer.json
- src/Codeception/Module/Symfony.php
- src/Codeception/Module/Symfony/ValidatorAssertionsTrait.php
Examples:
```php
$user = User::create('test@example.com', 'password', ['ROLE_ADMIN']);
$I->dontSeeViolatedConstraint($user);
$I->dontSeeViolatedConstraint($user, 'email');
$I->dontSeeViolatedConstraint($user, 'email', Email::class);
$I->dontSeeViolatedConstraint($user, 'password', NotBlank::class);
$user->setPassword('weak');
$I->seeViolatedConstraint($user, 'password', Length::class);
```
```php
$user = User::create('invalid_email', 'weak', ['ROLE_ADMIN']);
$I->seeViolatedConstraintsCount(2, $user);
$I->seeViolatedConstraintsCount(1, $user, 'email');
$I->seeViolatedConstraintMessage('is not a valid email', $user, 'email');
$user->setEmail('');
$I->seeViolatedConstraintMessage('should not be blank', $user, 'email');
```
> Added Symfony validator assertions

- composer.json
- src/Codeception/Module/Symfony.php
I'm replacing #4 with this.
In my last comment I expressed that I had problems with compatibility logic in lower versions of Symfony, but since the minimum compatible version is now 5.4 we can move on.
I require the `tests/bootstrap.php` file if it exists, otherwise I try to use dotEnv manually.
If all that fails I throw an exception telling the user what to do.
In the tests I performed this works regardless of whether or not you have `.env` and `.env.test` set in `codeception.yml`. 
This will also allow to remove these values from the [recipe](https://github.com/symfony/recipes-contrib/blob/8f56f2cee929025a5597b9e44d81fe90c4e7cd71/codeception/codeception/5.0/codeception.yml#L15) since they are now loaded automatically.
Closes #99.
> Require bootstrap.php if exists, to load all necessary .env files

- src/Codeception/Module/Symfony/SessionAssertionsTrait.php
> #165 login token

- src/Codeception/Module/Symfony/ParameterAssertionsTrait.php
I hardly have any parameters `set`, I define most of them via `bind`. That's why I'm adding this.
There is no way to grab a `bind`-Parameter, right?
> Update ParameterAssertionsTrait.php: Adding info about `bind`

- src/Codeception/Module/Symfony.php
- src/Codeception/Module/Symfony/BrowserAssertionsTrait.php
- src/Codeception/Module/Symfony/EventsAssertionsTrait.php
- src/Codeception/Module/Symfony/FormAssertionsTrait.php
- src/Codeception/Module/Symfony/MimeAssertionsTrait.php
- src/Codeception/Module/Symfony/SecurityAssertionsTrait.php
- src/Codeception/Module/Symfony/SessionAssertionsTrait.php
https://wiki.php.net/rfc/deprecate-implicitly-nullable-types deprecates implicitly nullable parameter types in PHP 8.4
> Declare nullable parameter types explicitly for PHP 8.4 compatibility

- src/Codeception/Module/Symfony/BrowserAssertionsTrait.php
- src/Codeception/Module/Symfony/DomCrawlerAssertionsTrait.php
- src/Codeception/Module/Symfony/FormAssertionsTrait.php
- src/Codeception/Module/Symfony/HttpClientAssertionsTrait.php
- src/Codeception/Module/Symfony/MailerAssertionsTrait.php
> Document new Symfony assertions

- src/Codeception/Module/Symfony/MailerAssertionsTrait.php
I will add a link to Mailpit, as soon as https://github.com/Codeception/codeception.github.com/pull/880 is merged.
> Update MailerAssertionsTrait.php: Adding Mailpit
